### ISSUE TITLE
Parser decisions

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMS#19]
Hi Rashid - please can you make a list of all the decisions taken in the parsers (e.g. if there are three sectors but no percentages - what percentage to we assign each sector) - as we will need to review these one by one

**Comment by raashidahmad** [comment]
@matmaxgeds 
1. The only decision taken so far regarding the data for Somalia is if there are no percentages for sectors, all the sectors get average of total by default.

**Comment by matmaxgeds** [comment]
Closed here - will continue on UI issues page
