### ISSUE TITLE
Docker - linux/multiarch

### ISSUE THREAD

**Issue by matmaxgeds** [somaliaims/Somali-AIMS#7]
The ToRs require that the AIMS can deploy on Linux as well as Windows servers - please shift to a multiarch setup so that the single AIMS image on the docker hub can be deployed either way

**Comment by matmaxgeds** [comment]
@raashidahmad please can I get an update on this?

**Comment by raashidahmad** [comment]
@matmaxgeds thanks for the recall. Sorry, i could not manage the time on weekend for this. I will try to manage the time for this on some weekend or will try to manage the time while being i am at Mogadishu.

**Comment by matmaxgeds** [comment]
Thanks @raashidahmad - let's aim for having it done and in use by me before the end of November - please make sure that you also demonstrate docker deployments on the new server to MoPIED so that they can compare options.

**Comment by somaliaims** [comment]
Hi @matmaxgeds,
As discussed, we will use a standard Linux image across all platforms. The image is created and shared on dockerhub. Will be updating image frequently at the end of every week.
